# Generated by Django 4.1.3 on 2023-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_alter_branch_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
