# Generated by Django 4.1.3 on 2023-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_alter_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
